---
title: "My English Activity Log : MEAL"
author:
  - name: "Berrehrah souhila" 
date: "02-05-2021"
categories:
  - "English for Science"
  - "M.E.A.L."
output: distill::distill_article
---


•	November. 30th: I decided to watch the movies and cartoons in English with the English translation, at the beginning it was difficult because i don't understand but I got used to it afterwards

•	January .30th: I discovered the youtube channel TED TALKS to learn English, it really motivated me to make more effort to improve my English skills so i subscribed to several channel which gives English lessons on youtube and I really find that these courses are very interesting


•	February. 17th: I downloaded the DUOLING application, on my phone which gives free lessons(oral and written), i really liked it because it is not boring at all it lets people learn the language while having fun and i downloaded AUDIO BOOKS application and i started  to listen to audio books to improve my pronunciation  and my listening skills

•	February .28th: I made some foreign friends who speak fluent English on the social network and i tried to speak English as much as possible


•	March. 17 th: I went to the library to buy books, and i bought my favorite book i have already read it but in French, this time i decided to read it in English it is the little prince who is a magnificent book.

•	April. 6th: I read different articles in English from different studies in completely different fields of biology (chemistry, physics) and learned a lot from these articles


•	April. 28th: here iam arriving at the last step of my blog and i wrote the conclusion, i learned a lot of things during the realization of my work, at the beginning it was hard for me especially the use of R language so that i can write and publish my articles but i hope that i managed to do at least the minimum.

  
