---
title: Article 7 "New anti-AB vaccine could help halt Alzheimer's progression, preclinical study finds"
description: |
  A new vaccine for Alzheimer’s disease .
author:
  - name: Souhila Berrehrah
    url:
      https://berrehrahsouhila.github.io/souhila.blog/: {}
date: 03-16-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


**I-SOURCE OF THE ARTICLE WITH PUBLICATION DATE AND WORD COUNT :**

**Source of the article :**
<https://www.sciencedaily.com/releases/2020/10/201020135637.htm> (October 20, 2020)

**Source of the study :** (Ge Song et al., 2020)

**Word count :** 622

**II- VOCABULARY :**

| Word from the text  | Synonym/definition in English                                                                                                                                                                                                                                                                                | French translation         |
| ------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | -------------------------- |
| Antigen             | A protein that can cause the body to react by producing an antibody that fights infection or disease                                                                                                                                                                                                         | Antigène                   |
| Antibody            | A protein produced in the blood or tissues in response to the presence of a specific foreign antigen. Antibodies provide immunity against certain microorganisms and toxins by binding with them and often by deactivating them. Also called immunoglobulin                                                  | Anticorps                  |
| Vaccine             | Any preparation used as a preventive inoculation to confer immunity against a specific disease, usually employing an innocuous form of the disease agent, as killed or weakened bacteria or viruses, to stimulate antibody production                                                                        | Vaccin                     |
| Dendritic cell      | Any of various white blood cells that have long projections from the cell body and function in the immune response by taking in and processing antigens and presenting them to T cells in lymph nodes, thus activating the T cells. Immature dendritic cells are found chiefly in skin and mucosal surfaces. | Les cellules dendritiques  |
| Aβ peptide          | Amyloid-beta peptide major neurotoxic component of extracellular deposits found in patients with Alzheimer disease                                                                                                                                                                                           | Le peptide amyloïde bêta   |
| Nerve cells         | Any of the cells of the nervous system. Nerve cells typically consist of a cell body, which contains a nucleus and receives incoming nerve impulses, and an axon, which carries impulses away from the cell body. Also called neuron                                                                         | Cellule nerveuse           |
| Immunomodulatory    | A substance that affects the functioning of the immune system                                                                                                                                                                                                                                                | Immunomodulateurs          |
| Bone marrow         | The soft tissue that fills most bone cavities and consists of yellowish fatty tissue or reddish vascular tissue. In adult mammals, the bone marrow of certain bones is the location of stem cells that give rise to the red blood cells, white blood cells, and platelets                                    | Moelle osseuse             |
| Innate immunity     | Immunity to disease that occurs as part of an individual's natural biologic makeup                                                                                                                                                                                                                           | Immunité naturelle         |
| Acquired immunity   | Immunity obtained either from the development of antibodies in response to exposure to an antigen, as from vaccination or an attack of an infectious disease, or from the transmission of antibodies, as from mother to fetus through the placenta or the injection of antiserum                             | Immunité acquise           |
| Transgenic          | Pertaining to, or containing a gene or genes transferred from another species                                                                                                                                                                                                                                | Transgénique               |
| Cytokine            | Any of various proteins, such as the interleukins and lymphokines, that are released by cells of the immune system and act in intercellular communication, especially in regulating inflammation and the immune response                                                                                     | Cytokine                   |
|                     |                                                                                                                                                                                                                                                                                                              |                            |

**III- ANALYSIS TABLE ABOUT THE STUDY :**

| Researchers?                        | University of  South Florida (USF Health), Lead author : Ge Song                                                                                                                                             |
| ----------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| Published in? when (if mentioned)?  | Science Daily, October 20, 2020                                                                                                                                                                              |
|  General topic                      | Discovery of new vaccine E22W42 DC for Alzheimer's disease                                                                                                                                                   |
|  Procedure/ what was examined       | To test the new vaccine that researchers developed using dendritic cells and modified Aβ peptide ( antigen) which  derived from mouse, the scientists used 3 different groups of transgenic mice (APP / PS1) |
|                                     | – The first group : is  vaccinated with the new vaccine E22W42 DC                                                                                                                                            |
|                                     | – The second group received Aβ peptide                                                                                                                                                                       |
|                                     | – The third group received dendritic cells without Aβ peptide                                                                                                                                                |
|                                     | – The fourth group is a control group ( didn’t treated with anything and they are in good heath)                                                                                                             |
| Conclusions/ discovery              | The new vaccine showed a great results on animals model  so researchers hope that this new vaccine will help people against Alzheimer’s disease  and other neurodegenerative disease                         |
|  Remaining questions                | /                                                                                                                                                                                                            |
|                                     |                                                                                                                                                                                                              |
